site_name: A Google Chart Sample
dev_addr: 0.0.0.0:8080
site_description: Examples of integrating MkDocs with 3rd Party Libraries.
site_author: Katz Kawai
site_url: http://cyan0708.github.io/mkdocs03/
repo_url: https://github.com/cyan0708/mkdocs03/
extra_javascript: []
extra_css: []
markdown_extensions: []
# git@github.com:cyan0708/mkdocs03.git
pages:
- ホーム: index.md
- 本サイトについて: about.md
- 自己紹介: profile.md
- 'サンプル': 'samples/index.md'
